#!/usr/bin/env python3
"""
MIRRA Content Batch Generator — Auto-generated by brand-system-architect.sh
Generated: 2026-03-08T22:45:45
Brand: mirra

Architecture: Multi-model pipeline (Pipeline A/B/C) with parallel execution.
Reference: Mirra's cat06_batch.py (Q-batch v8, 16 templates)

Usage:
  python3 batch.py                    # Run all templates
  python3 batch.py <key>              # Run single template
  python3 batch.py --audit <path>     # Audit existing output
"""
import os
import sys
import json
import subprocess
import time
from pathlib import Path
from PIL import Image

# Import brand filter
sys.path.insert(0, os.path.dirname(__file__))
from filter import (
    full_pipeline, fit_target, brand_filter, stamp_logo, add_grain,
    _treat_product_photo, FILTER_PRESETS
)

###############################################################################
# Config
###############################################################################
BRAND_DIR = Path("/Users/jennwoeiloh/.openclaw/brands/mirra")
SYSTEM_DIR = BRAND_DIR / "system"
REF_DIR = BRAND_DIR / "references"
OUTPUT_DIR = SYSTEM_DIR / "output"
LOGO_PATH = None  # Set to logo file path when available

BATCH_PREFIX = "A"  # Increment per batch: A, B, C, ...
TARGET_W, TARGET_H = 1080, 1350  # 4:5 portrait (Instagram default)

###############################################################################
# Template Registry
# Fill in from TEMPLATE-REGISTRY.md after Phase 3
###############################################################################
TEMPLATES = {
    # "key": {
    #     "label": "Human-readable name",
    #     "pipeline": "a",  # a, b, b_two_pass, c
    #     "model": "nano",  # nano, flux, two_pass, ideogram
    #     "ref_image": "references/category/filename.png",
    #     "product_photo": None,  # path or None
    #     "product_zone_ar": (3, 4),  # aspect ratio for product crop
    #     "prompt": "...",
    #     "filter_preset": "default",
    #     "logo_in_design": False,
    #     "top_bias": 0.3,
    #     "notes": "",
    # },
}

###############################################################################
# Model Dispatch
###############################################################################

def _call_fal(endpoint, payload):
    """Call fal.ai API. Requires FAL_KEY in environment."""
    import fal_client
    result = fal_client.subscribe(endpoint, arguments=payload)
    return result


def _generate_pipeline_a(template):
    """Pipeline A: Text/surface swap only."""
    model = template.get("model", "nano")
    ref_path = str(BRAND_DIR / template["ref_image"])

    if model == "nano":
        result = _call_fal("fal-ai/nano-banana-pro/edit", {
            "image_url": ref_path,
            "prompt": template["prompt"],
            "resolution": "2K",
        })
    elif model == "flux":
        result = _call_fal("fal-ai/flux-pro/kontext/max", {
            "image_url": ref_path,
            "prompt": template["prompt"],
            "guidance_scale": 4.0,
            "num_inference_steps": 40,
        })
    elif model == "two_pass":
        # Step 1: FLUX for surface
        flux_result = _call_fal("fal-ai/flux-pro/kontext/max", {
            "image_url": ref_path,
            "prompt": template.get("flux_prompt", template["prompt"]),
        })
        # Step 2: NANO for text correction
        result = _call_fal("fal-ai/nano-banana-pro/edit", {
            "image_url": flux_result["images"][0]["url"],
            "prompt": template.get("nano_prompt", template.get("text_fix_prompt", "")),
        })
    else:
        raise ValueError(f"Unknown model for Pipeline A: {model}")

    return result


def _generate_pipeline_b(template):
    """Pipeline B: Product photo as INPUT."""
    product_path = str(BRAND_DIR / template["product_photo"])
    zone_ar = template.get("product_zone_ar", (3, 4))
    treated = _treat_product_photo(product_path, zone_ar=zone_ar)
    treated_path = str(OUTPUT_DIR / "_treated_product.png")
    treated.save(treated_path)

    ref_path = str(BRAND_DIR / template["ref_image"])
    result = _call_fal("fal-ai/nano-banana-pro/edit", {
        "image_url": ref_path,
        "prompt": template["prompt"],
        "reference_images": [treated_path],
        "resolution": "2K",
    })
    return result


def _generate_pipeline_c(template):
    """Pipeline C: Product IS the background."""
    product_path = str(BRAND_DIR / template["product_photo"])
    treated = _treat_product_photo(product_path, zone_ar=(4, 5), warm_tint=0.12)
    treated_path = str(OUTPUT_DIR / "_treated_bg.png")
    treated.save(treated_path)

    ref_path = str(BRAND_DIR / template["ref_image"])
    result = _call_fal("fal-ai/nano-banana-pro/edit", {
        "image_url": ref_path,
        "prompt": template["prompt"],
        "reference_images": [treated_path],
    })
    return result


###############################################################################
# Build
###############################################################################

def _build(key):
    """Build a single template."""
    if key not in TEMPLATES:
        print(f"ERROR: Unknown template key: {key}")
        return None

    t = TEMPLATES[key]
    print(f"Building {BATCH_PREFIX}{key}: {t['label']}...")

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    out_path = OUTPUT_DIR / f"{BATCH_PREFIX}-{key}.png"

    pipeline = t.get("pipeline", "a")
    try:
        if pipeline == "a":
            result = _generate_pipeline_a(t)
        elif pipeline == "b":
            result = _generate_pipeline_b(t)
        elif pipeline == "b_two_pass":
            # FLUX surface + NANO product
            flux_result = _call_fal("fal-ai/flux-pro/kontext/max", {
                "image_url": str(BRAND_DIR / t["ref_image"]),
                "prompt": t.get("flux_prompt", t["prompt"]),
            })
            treated = _treat_product_photo(
                str(BRAND_DIR / t["product_photo"]),
                zone_ar=t.get("product_zone_ar", (1, 1))
            )
            treated_path = str(OUTPUT_DIR / "_treated_product.png")
            treated.save(treated_path)
            result = _call_fal("fal-ai/nano-banana-pro/edit", {
                "image_url": flux_result["images"][0]["url"],
                "prompt": t.get("nano_prompt", t["prompt"]),
                "reference_images": [treated_path],
            })
        elif pipeline == "c":
            result = _generate_pipeline_c(t)
        else:
            print(f"ERROR: Unknown pipeline: {pipeline}")
            return None

        # Download result image
        img_url = result["images"][0]["url"]
        import urllib.request
        urllib.request.urlretrieve(img_url, str(out_path).replace(".png", "-raw.png"))
        raw_img = Image.open(str(out_path).replace(".png", "-raw.png"))

        # Text fix pass if specified
        if t.get("text_fix_prompt"):
            fix_result = _call_fal("fal-ai/nano-banana-pro/edit", {
                "image_url": img_url,
                "prompt": t["text_fix_prompt"],
            })
            img_url = fix_result["images"][0]["url"]
            urllib.request.urlretrieve(img_url, str(out_path).replace(".png", "-textfix.png"))
            raw_img = Image.open(str(out_path).replace(".png", "-textfix.png"))

        # Post-processing pipeline
        final = full_pipeline(
            raw_img,
            preset=t.get("filter_preset", "default"),
            logo_path=LOGO_PATH,
            logo_in_design=t.get("logo_in_design", False),
            target_w=TARGET_W,
            target_h=TARGET_H,
            top_bias=t.get("top_bias", 0.3),
        )
        final.save(str(out_path))
        print(f"  Saved: {out_path}")
        return str(out_path)

    except Exception as e:
        print(f"  ERROR building {key}: {e}")
        return None


def build_all():
    """Build all templates in parallel."""
    import multiprocessing
    keys = list(TEMPLATES.keys())
    if not keys:
        print("No templates defined yet. Fill in TEMPLATES dict from TEMPLATE-REGISTRY.md")
        return

    print(f"Building {len(keys)} templates (parallel)...")
    with multiprocessing.Pool(min(8, len(keys))) as pool:
        results = pool.map(_build, keys)

    success = sum(1 for r in results if r is not None)
    print(f"Done: {success}/{len(keys)} succeeded")


###############################################################################
# Main
###############################################################################
if __name__ == "__main__":
    if len(sys.argv) > 1:
        key = sys.argv[1]
        if key == "--audit":
            print("Audit mode not yet implemented. See Phase 6.")
        else:
            _build(key)
    else:
        build_all()
