#!/usr/bin/env python3
"""
MIRRA Brand Filter — Auto-generated by brand-system-architect.sh
Generated: 2026-03-08T22:45:45
Brand: mirra

Post-processing stack (ALWAYS in this order):
  1. fit_target(img, top_bias)  -- crop/resize to target aspect ratio
  2. brand_filter(img, mode)    -- overlay, desat, warmth
  3. stamp_logo(img)            -- ONLY if logo_in_design=False
  4. add_grain(img, strength)   -- ALWAYS LAST
"""
import numpy as np
from PIL import Image, ImageEnhance, ImageDraw, ImageFont
import os

###############################################################################
# Brand Color Palette (from DNA.json)
###############################################################################
PRIMARY_BLUSH = (248, 190, 205)  # #F8BECD
DUSTY_ROSE = (235, 170, 189)  # #EBAABD
CRIMSON_ACCENT = (172, 55, 75)  # #AC374B
WARM_CREAM = (255, 245, 238)  # #FFF5EE
OVERLAY_BG = (245, 220, 210)  # #F5DCD2
HOT_GLITTER = (232, 99, 138)  # #E8638A
NEUTRAL_BASE = (250, 246, 241)  # #FAF6F1

###############################################################################
# Core Functions
###############################################################################

def _hex_to_rgb(hex_str):
    """Convert hex color to RGB tuple."""
    h = hex_str.lstrip('#')
    return tuple(int(h[i:i+2], 16) for i in (0, 2, 4))


def fit_target(img, target_w=1080, target_h=1350, top_bias=0.3):
    """
    Crop and resize image to target dimensions.
    top_bias: 0.0 = crop from top, 0.5 = center, 1.0 = crop from bottom.
    For UI screenshots, use top_bias=0.15 to preserve nav bars.
    """
    src_w, src_h = img.size
    target_ar = target_w / target_h
    src_ar = src_w / src_h

    if abs(src_ar - target_ar) < 0.01:
        return img.resize((target_w, target_h), Image.LANCZOS)

    if src_ar > target_ar:
        # Source is wider — crop sides
        new_w = int(src_h * target_ar)
        left = (src_w - new_w) // 2
        img = img.crop((left, 0, left + new_w, src_h))
    else:
        # Source is taller — crop top/bottom with bias
        new_h = int(src_w / target_ar)
        top = int((src_h - new_h) * top_bias)
        img = img.crop((0, top, src_w, top + new_h))

    return img.resize((target_w, target_h), Image.LANCZOS)


def brand_filter(img, overlay_rgb=None, overlay_alpha=42, desat=0.80, brightness=1.04, contrast=0.95):
    """
    Apply brand filter stack.
    overlay_rgb: tuple (R, G, B) — brand overlay color. Uses palette default if None.
    overlay_alpha: 0-255. Higher = stronger overlay.
    desat: 0.0 = full gray, 1.0 = no change.
    """
    img = img.convert("RGB")
    arr = np.array(img, dtype=np.float64) / 255.0

    # 1. Brand overlay tint
    if overlay_rgb is None:
        # Use first palette color as default overlay
        overlay_rgb = OVERLAY_BG if 'OVERLAY_BG' in dir() else PRIMARY_BLUSH if 'PRIMARY_BLUSH' in dir() else (245, 220, 210)
    ov = np.array(overlay_rgb, dtype=np.float64) / 255.0
    alpha = overlay_alpha / 255.0
    arr = arr * (1.0 - alpha) + ov * alpha

    # 2. Desaturation
    gray = np.mean(arr, axis=2, keepdims=True)
    arr = gray * (1.0 - desat) + arr * desat

    # 3. Brightness + contrast
    arr = np.clip(arr * brightness, 0, 1)
    mean = np.mean(arr)
    arr = mean + (arr - mean) * contrast
    arr = np.clip(arr, 0, 1)

    return Image.fromarray((arr * 255).astype(np.uint8))


def stamp_logo(img, logo_path=None, position="bottom-right", scale=0.08, margin=30):
    """
    Stamp brand logo on image.
    Only call if logo_in_design=False.
    """
    if logo_path is None or not os.path.exists(logo_path):
        return img

    logo = Image.open(logo_path).convert("RGBA")
    logo_w = int(img.width * scale)
    logo_h = int(logo.height * (logo_w / logo.width))
    logo = logo.resize((logo_w, logo_h), Image.LANCZOS)

    pos_map = {
        "bottom-right": (img.width - logo_w - margin, img.height - logo_h - margin),
        "bottom-left": (margin, img.height - logo_h - margin),
        "bottom-center": ((img.width - logo_w) // 2, img.height - logo_h - margin),
        "top-right": (img.width - logo_w - margin, margin),
        "top-left": (margin, margin),
    }
    pos = pos_map.get(position, pos_map["bottom-right"])

    canvas = img.convert("RGBA")
    canvas.paste(logo, pos, logo)
    return canvas.convert("RGB")


def add_grain(img, strength=0.014):
    """
    Add film grain. ALWAYS apply LAST in the pipeline.
    strength: 0.014 for UI designs, 0.022 for flat typography backgrounds.
    """
    arr = np.array(img, dtype=np.float64)
    noise = np.random.normal(0, strength * 255, arr.shape)
    arr = np.clip(arr + noise, 0, 255)
    return Image.fromarray(arr.astype(np.uint8))


def _treat_product_photo(product_path, zone_ar=(3, 4), warm_tint=0.08, desat=0.10):
    """
    Prepare a product photo for Pipeline B/C insertion.
    Crops to zone aspect ratio, applies warm tint + slight desaturation.
    Zone ARs: (3,4) portrait, (16,9) landscape banner, (4,3) landscape, (1,1) square.
    """
    food = Image.open(product_path).convert("RGB")

    # Center crop to target AR
    src_w, src_h = food.size
    target_ar = zone_ar[0] / zone_ar[1]
    src_ar = src_w / src_h
    if src_ar > target_ar:
        new_w = int(src_h * target_ar)
        left = (src_w - new_w) // 2
        food = food.crop((left, 0, left + new_w, src_h))
    else:
        new_h = int(src_w / target_ar)
        top = (src_h - new_h) // 2
        food = food.crop((0, top, src_w, top + new_h))

    # Warm tint
    arr = np.array(food, dtype=np.float64) / 255.0
    warm_overlay = np.ones_like(arr)
    warm_overlay[:, :, 0] = 1.0    # R
    warm_overlay[:, :, 1] = 0.85   # G (amber)
    warm_overlay[:, :, 2] = 0.65   # B
    arr = arr + warm_tint * (warm_overlay - arr)

    # Partial desaturation
    gray = np.mean(arr, axis=2, keepdims=True)
    arr = gray * desat + arr * (1.0 - desat)
    arr = np.clip(arr, 0, 1)

    return Image.fromarray((arr * 255).astype(np.uint8))


###############################################################################
# Filter Presets (customize per category after Phase 2 analysis)
###############################################################################

FILTER_PRESETS = {
    "default": {"overlay_alpha": 42, "desat": 0.80, "brightness": 1.04, "contrast": 0.95, "grain": 0.014},
    "typography": {"overlay_alpha": 25, "desat": 0.88, "brightness": 1.02, "contrast": 0.97, "grain": 0.012},
    "photo_heavy": {"overlay_alpha": 50, "desat": 0.75, "brightness": 1.04, "contrast": 0.95, "grain": 0.016},
    "gradient": {"overlay_alpha": 0, "desat": 1.0, "brightness": 1.0, "contrast": 1.0, "grain": 0.016},
}


def full_pipeline(img, preset="default", logo_path=None, logo_in_design=False,
                  target_w=1080, target_h=1350, top_bias=0.3):
    """
    Run the complete post-processing pipeline in correct order.
    Order: fit -> filter -> logo -> grain (NEVER reorder)
    """
    p = FILTER_PRESETS.get(preset, FILTER_PRESETS["default"])

    # 1. Fit
    img = fit_target(img, target_w, target_h, top_bias)

    # 2. Brand filter
    img = brand_filter(img,
                       overlay_alpha=p["overlay_alpha"],
                       desat=p["desat"],
                       brightness=p["brightness"],
                       contrast=p["contrast"])

    # 3. Logo (only if not already in design)
    if not logo_in_design and logo_path:
        img = stamp_logo(img, logo_path)

    # 4. Grain (ALWAYS LAST)
    img = add_grain(img, strength=p["grain"])

    return img


if __name__ == "__main__":
    import sys
    if len(sys.argv) < 2:
        print("Usage: python3 filter.py <image_path> [preset] [output_path]")
        sys.exit(1)
    img = Image.open(sys.argv[1])
    preset = sys.argv[2] if len(sys.argv) > 2 else "default"
    out = sys.argv[3] if len(sys.argv) > 3 else sys.argv[1].replace(".png", "-filtered.png")
    result = full_pipeline(img, preset=preset)
    result.save(out)
    print(f"Saved: {out}")
